#!/usr/bin/env bash
set -ex
systemctl --user stop polybar@single.service
xrandr --output eDP-1 --auto --output DP-2-3 --right-of eDP-1 --auto --scale 1
systemctl --user start polybar@main.service polybar@secondary.service
~/.fehbg
