#!/usr/bin/env bash
set -ex
systemctl --user stop polybar@main.service polybar@secondary.service
xrandr --output eDP-1 --auto --output DP-2-3 --off
systemctl --user start polybar@single.service
~/.fehbg
